### ISSUE TITLE
Error with Grails 2.4.5

### ISSUE THREAD

**Issue by biohazardxxx** [timyates/groovy-common-extensions#16]
General error during conversion: Conflicting module versions. Module [groovy-all is loaded in version 2.3.11 and you are trying to load version 2.2.1
  [groovyc]
Maybe remove of "compile      'org.codehaus.groovy:groovy-all:2.2.1'" in build.gradle would do the trick?

**Comment by timyates** [comment]
Problem is, that can't be removed as then it won't compile ;-)

I'll have a think if there's a way that doesn't involve me rebuilding it
for all versions of groovy ;-)

**Comment by timyates** [comment]
As a workaround, you should be able to extract the
groovy-common-extensions-0.6.0.jar
<http://search.maven.org/remotecontent?filepath=com/bloidonia/groovy-common-extensions/0.6.0/groovy-common-extensions-0.6.0.jar>
jar
file out of your maven cache (or wherever it's been downloaded from), and
just add that to your classpath

That *should* work...  But I've not had a coffee yet, so YMMV ;-)

**Comment by biohazardxxx** [comment]
Adding

		compile 'com.bloidonia:groovy-common-extensions:0.6.0'
to buildconfig at dependencies did the trick. Thanks!
